FROM nvidia/cuda:10.2-base-ubuntu18.04

# Install some basic utilities
RUN apt-get update \
 && apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
 && rm -rf /var/lib/apt/lists/*


RUN apt-get update \
  && apt-get install -y bash-completion

# Create a working directory
RUN mkdir /workspace
WORKDIR /workspace

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /workspace
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user

# Install Miniconda and Python 3.8
ENV CONDA_AUTO_UPDATE_CONDA=false
ENV PATH=/home/user/miniconda/bin:$PATH
RUN curl -sLo ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py38_4.8.3-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh \
 && conda install -y python==3.8.1 \
 && conda clean -ya

# CUDA 10.2-specific steps
RUN conda install -y -c pytorch pytorch=1.6.0 \
    cudatoolkit=10.2 \
    # "pytorch=1.5.0=py3.8_cuda10.2.89_cudnn7.6.5_0" \
    # "torchvision=0.6.0=py38_cu102" \
  && conda install -c conda-forge jupyterlab \
  && conda install pandas=1.1.1 \
#   && conda install -c rapidsai rapids=0.14.0 \
  && conda clean -ya

## MOVE ABOVE
USER root
RUN apt-get update \
  && apt-get install -y build-essential libsndfile-dev software-properties-common

COPY requirements.txt /tmp/requeriments.txt
RUN pip install -r /tmp/requeriments.txt

ENV SHELL=/bin/bash
# RUN pip install -r requeriments.txt